# Generated by Django 4.2.2 on 2023-06-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='info',
            field=models.TextField(max_length=20000),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('length', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main_app.album')),
            ],
        ),
    ]
